services:
  # Notre application Spring Boot
  backend:
    build: . # Construit l'image à partir du Dockerfile local
    container_name: weline_backend
    ports:
      - "8088:8080" # Expose le port de l'app sur la machine hôte
    environment:
      # On configure l'app pour qu'elle se connecte aux autres conteneurs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/weline_db
      - SPRING_DATASOURCE_USERNAME=weline
      - SPRING_DATASOURCE_PASSWORD=supersecret
      - SPRING_REDIS_HOST=redis_cache
    depends_on:
      - postgres_db
      - redis_cache
    networks:
      - weline-network

      # La base de données PostgreSQL
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=weline_db
      - POSTGRES_USER=weline
      - POSTGRES_PASSWORD=supersecret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optionnel : pour se connecter à la DB depuis la machine locale
    networks:
      - weline-network

  # Le cache Redis
  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - weline-network


networks:
  weline-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: