services:

  backend:
    build: .
    container_name: weline_backend
    restart: always
    ports:
      - "8088:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:${PGPORT}/${PGDATABASE}
      - SPRING_DATASOURCE_USERNAME=${PGUSER}
      - SPRING_DATASOURCE_PASSWORD=${PGPASSWORD}
      - SPRING_REDIS_HOST=${REDISHOST}
    depends_on:
      - postgres_db
      - redis_cache
    networks:
      - weline-network


  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optionnel : pour se connecter Ã  la DB depuis la machine locale
    networks:
      - weline-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - weline-network

  adminer:
    image: adminer
    container_name: adminer_gui
    restart: always
    ports:
      - "8081:8080"
    networks:
      - weline-network
    depends_on:
      - postgres_db

networks:
  weline-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: